### ISSUE TITLE
イベントマスを無理やり突破できることがある

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#1]
2Fギンいろのきりがおりてくるところで確認。
ナナメに押しながら歩くことで
・イベント発生せずに突破できることがある
・イベント発生後に戻されるはずが曲った先に進めることがある

**Comment by daradarach** [comment]
右方向限定っぽいです(PCブラウザ版@Firefox)

**Comment by shiromofufactory** [comment]
ありがとうございます。原因わかったので修正しました！

**Comment by daradarach** [comment]
修正されてそうなことを確認しました
