### ISSUE TITLE
ニューゲームからキャンセルを押しても最初の開始画面に戻らない

### ISSUE THREAD

**Issue by jinbei** [shiromofufactory/finardry#11]
可能でしたら、ニューゲームを選択後、キャンセルすると最初の画面に戻ると助かります。

**Comment by shiromofufactory** [comment]
すみません、なんだかすごい勢いで要望を挙げられてますが、不具合や著しく不便というレベルではなく個人の好みかな？と思われるレベルのものは対応していたらキリがないので対応するつもりはありません。

何か強い理由がありますでしょうか？

**Comment by jinbei** [comment]
個人の好みですので、取り下げます。
