### ISSUE TITLE
提案:広告表示

### ISSUE THREAD

**Issue by jinbei** [shiromofufactory/finardry#12]
これだけ良いものを作成されてますので、運用や開発費のために、ゲームの画面外の黒い箇所に「忍者AdMax」という広告を表示されてはいかがでしょうか？

https://hiroshi-music.com/ninjya-admax/

**Comment by shiromofufactory** [comment]
ありがとうございます。
ただこの作品の性質上、そういうわけにはいかないので（あまり自分で明言したくはないのですが、楽曲等の正当な著作権を保有している会社または個人から公開停止を要請された場合対応せざるを得ないです）見送らせてください。
