### ISSUE TITLE
PC版キーボードのリセットコマンドがWindows標準機能と被っている

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#13]
Alt+Escはウィンドウ切り替えなので被っている
自分の環境ではリセットできなかった。

ちなみにCtrl+Escはスタートメニューを開くになる。
F2～F10あたりがよさそう？

**Comment by shiromofufactory** [comment]
おおっと・・・

Esc単体だと誤操作があるからという指摘で変更したのですが、自分がMacユーザーでその辺疎くてわかりませんでした。
ちなみにShift＋Escでもダメでしょうか？

FnキーはMac側で単体で意味が割り当てられていることが多いのでできるだけ避けたく。

**Comment by daradarach** [comment]
Shift+Escについて

Firefoxではabout:processesのショートカットでした。

宗教上の理由でChromeは入れてないんですが、Microsoft Chromium Edgeにおいてはブラウザのタスクマネージャが開くようです。

**Comment by daradarach** [comment]
すごい個人的なことを言えば、一般的？にはZXCあたりに決定キャンセルメニューあたりを配置することが多いとか、WASDが移動の上下左右に割り当てられることが多いとかの中で、本ゲームのASWという配置にはやや戸惑いもありましたが慣れたらイケるやろ、で無視していいんじゃないかなというか。

**Comment by shiromofufactory** [comment]
たしかにそうかもですね。 > 一般的？にはZXCあたりに決定キャンセルメニューあたりを配置することが多い
バーチャルパッドと配置を近似させたかったのでWASDから選びました。
私もそれなりにPCでゲームすることがありますが、３キーくらいまでならだいたいどんな配置でも慣れられるので問題ないかなという結論に至っています。

あとEscのほうもありがとうございます。
なんだか不自然ですが、機能かぶりがないであろう「Esc+1」にしました。。

**Comment by daradarach** [comment]
単発キー出ないため暴発しづらく、他と何か被ってもないので良さそうですね。
