### ISSUE TITLE
BGM/SEの音量調整機能が欲しい

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#14]
BGM/SEの音量調整機能が欲しい
可能なら別々で調整できればBGMなしSEありにしたりできる

**Comment by shiromofufactory** [comment]
使用しているゲームエンジンの機能的に上記はちょっと難しいです。
ただ、一部ブラウザ（Kiwi？）でBGMがまともに再生できないという報告があったのでBGM OFF機能だけは入れようと思っています。SE OFFは演出に影響してしまいちょっと面倒なので、SEもOFFしたい人は端末で消音してもらえばいいかなと。（BGMは流したいけどSEいらん、という人はあんまりいないかと。）

**Comment by shiromofufactory** [comment]
2023/10/26のバージョンで上記のBGM OFF機能を追加したため、クローズさせていただきます。

**Comment by daradarach** [comment]
BGMだけOFFじゃなくて音全部OFFになったんですね。
(カッコ書きの中身から、BGMなしでSEだけ聞けることを少し期待してました)
でもゲーム側でON/OFF弄れるのはありがたいです、ありがとうございました

**Comment by shiromofufactory** [comment]
いえ、BGMだけです。SEは残しています。
もしかすると「SE」の定義が違うかもしれません。エンカウント時や勝利時のジングルはBGM扱いで、ボタンを押したときの「ポッ」という音やドアを開けたときの音は鳴っているはずです。（いったんreopenします）

**Comment by daradarach** [comment]
ごめんなさい勘違いでした…カーソル移動時に音が鳴ってたと思い込んでいて、ああ鳴らなくなったなと思ったらちゃんと決定時は鳴ってました。失礼しました。
