### ISSUE TITLE
Mobile version need reset button , etc

### ISSUE THREAD

**Issue by magussiro** [shiromofufactory/finardry#15]
I have clear this game two times and defeated werdna,It's a awesome game !

The first time I spent 7 hour to clear game ,but I don't know how to throw werdna amulet,somehow I lost werdna amulet, so I beat werdna again. the first time defeat can reward huge exp from castle, and the other characters also can get exp from castle, so I decide to play new game.

The second time I spent 1h40m to clear. turnout when your character change alignment and back to the castle, It would take all you equipped items to the gilgamesh's bar,normally the game would dress off your equipped items when you organize your party. maybe I can reproduce werdna amulet ? 

The plan is make full of different characters, go to the dungeon.gain exp when you need.  use combat and flee to change alignment, when someone change alignment, beat werdna!

Change alignment always takes times ... it make hundreds of flee times. maybe two hundred to five hundred. it would takes 10 mins. when you change alignment, equip werdna amulet and back to the castle. the changer would automated kick off the party. you need to use the rest of them to fight werdna, because when you reorganize your party, It would automated dress off all your characters equipped items.therefore you need to use 4 member to beat werdna. Yes, it would be difficult ,but no pain no gain. the 4th time to defeat werdna it's hardest because my party levels are 15 average.but the reward is huge,Just as I thought, i got second werdna amulet, and repeat 3 times, I have total 5 werdna amulets. 

here's my screenshot
5 werdna amulets
![197886](https://github.com/shiromofufactory/finardry/assets/15204888/4cf0885a-fccd-4072-845f-a39957143a88)

party level, 2 merber is innocent(not change jobs)
![197885](https://github.com/shiromofufactory/finardry/assets/15204888/d2aabe72-fa3e-4218-971a-cec6fc2dbc9c)

again, thanks to make this awesome game!

by the way, mobile version need reset button on the screen to reset, it take 20 second for one rest.

**Comment by shiromofufactory** [comment]
Thanks for playing so enthusiastically. It's a great accomplishment!

As for the reset button on the mobile, currently it can be accomplished by pressing 4 buttons at the same time. However, since it is a difficult operation, I am contemplating changing it so that it can be reset by long pressing the top button that is not used in the game.
What do you think?

**Comment by magussiro** [comment]
sounds good for me!

**Comment by shiromofufactory** [comment]
I have incorporated this issue in ver. 20201027 and will close it. Thanks for the advice.
