### ISSUE TITLE
KADORTOを戦闘中使用可能に

### ISSUE THREAD

**Issue by Feanorjp** [shiromofufactory/finardry#16]
シナリオによってキャンプ中じゃないと使えなかったり、戦闘中も使えたり扱いの違うカドルトですが
このゲームの難易度からすると使えた方がいいかなと思いました。

**Comment by shiromofufactory** [comment]
お返事遅れて申し訳ありません。
たしかにディとの差別化のためにも、カドルトは戦闘中使用できてもいいかもしれません。
ちょっと検討しますが、とりいそぎお返事まで。

**Comment by shiromofufactory** [comment]
ver.20231031で反映させていただきました！ありがとうございました。
issueをクローズさせていただきます。
