### ISSUE TITLE
モバイル版でキーの表示

### ISSUE THREAD

**Issue by jinbei** [shiromofufactory/finardry#17]
モバイル版で、axwキーを表示してくださると、誤操作が減り助かります。

**Comment by shiromofufactory** [comment]
ご指摘の点ごもっともなのですが、残念ながら対応が難しいです。
理由として、バーチャルパッドはFinardry独自に表示しているわけではなく、使用しているゲームエンジン「Pyxel」が提供しているものをそのまま使っています。これは現バージョンだと表示をカスタマイズすることができない仕様になっているためです。

**Comment by jinbei** [comment]
なるほど。承知しました。本件、クローズします。
