### ISSUE TITLE
地下一階に袋小路が？

### ISSUE THREAD

**Issue by yandod** [shiromofufactory/finardry#18]
データファイル上は`---`になっている座標かと思いますが、テレポーターで閉じ込められたようです。
https://www.threads.net/@luvtechno/post/CzBhJylS8PE

データファイルにはこの空間は存在していないように見えます。
https://github.com/shiromofufactory/finardry/blob/master/src/maps/b1.txt

連続する壁の中に空間を入れる処理もなさそうなことを見ました。
https://github.com/shiromofufactory/finardry/blob/master/src/actor.py#L30

テレポートの際は空白の場所になるまでリトライが入っているように見えます
https://github.com/shiromofufactory/finardry/blob/master/src/main.py#L2749

![image](https://github.com/shiromofufactory/finardry/assets/103903/c10b4622-2f36-4e09-928b-68930fc71f28)

**Comment by shiromofufactory** [comment]
！！
ナイス発見ありがとうございます。設定ミスです。
明日リリースの予定があるので、マップデータ直します（壁で潰してテレポートできないようにします）。

**Comment by yandod** [comment]
見ている場所が違ったことを理解しました。
ここですね。
<img width="448" alt="スクリーンショット 2023-10-30 23 47 30" src="https://github.com/shiromofufactory/finardry/assets/103903/2e689627-f50c-4ac5-9925-d0b5c1bcf756">

**Comment by luvtechno** [comment]
現象に遭遇した者です。データの問題だったことがわかってよかったです！

**Comment by shiromofufactory** [comment]
お騒がせしました。クローズします。
