### ISSUE TITLE
GOLD所持上限UP

### ISSUE THREAD

**Issue by Feanorjp** [shiromofufactory/finardry#19]
村正や聖なる鎧が店売り25万、購入50万なのに所持金が999999でカンストしてしまうのは少ない。
表示はともかく内部的にはもう1桁増やしていただきたい

**Comment by Feanorjp** [comment]
既出でしたね。売却するとアイテム無限が在庫するようになるのとのバランスなのかも、とは思いつつだったので了解です。

**Comment by shiromofufactory** [comment]
Closedのissueをわざわざ確認いただき、恐れ入ります。
わからなくもないのですが、その段階までいくともはやゲームに差し支えはなくプレイヤの満足度（個人差あると思います）くらいの差でしかないので、見送らせてもらいました。
（やりこんでくださっている方が多いのは想定外でしたが・・）
