### ISSUE TITLE
今呼び出されたモンスターが行動したように見えることがある

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#2]
2Fクリーピングコインで確認
クリーピングコイン3匹の状態で1匹目が仲間を呼んで4匹になった際、最後に現れた4匹目が行動した。
(4匹目が現れたことで後衛になった扱いか、4匹ともが行動することはなかった)
もうちょっと確認が必要そう

**Comment by shiromofufactory** [comment]
これは既知の内容でした。面白いのであえてそのままにしています・・

**Comment by daradarach** [comment]
グレーターデーモンあたりで、
3匹→先に行動して1匹殺す(残2)→残る2匹が仲間を呼ぶ(残4)→呼び出された奴が即行動して仲間を呼ぶ(残5)みたいなことが起きますね。
養殖してるとおいしいのでこのままでもいいのかなと思います。
