### ISSUE TITLE
job change need learn spell for current level

### ISSUE THREAD

**Issue by magussiro** [shiromofufactory/finardry#20]
Most wizardry or wizard-like games have implemented this mechanism. If you learn a spell at a certain character level, it will remain with your character, regardless of any subsequent job changes. For instance, in the NES version of Wizardry, if a character, such as a priest, learns a level 6 spell at once, and later changes their job to a ninja, they will begin to learn other level 6 priest spells once they reach character level 11.

reference:
https://w.atwiki.jp/wiz-fo/pages/278.html

screenshots
![198227_0](https://github.com/shiromofufactory/finardry/assets/15204888/75ef2b65-a308-41c5-9d19-7baf5d67fe6e)
![198226_0](https://github.com/shiromofufactory/finardry/assets/15204888/ae008cff-2256-4840-b2ea-e3581f6c05a1)

**Comment by shiromofufactory** [comment]
Thanks for letting me know, Finardry's spell acquisition system is similar to Wizardry's, but slightly different, for example, spell acquisition levels depend on "intelligence" and "piety". I have taken this into consideration and will keep the current specifications.

**Comment by Feanorjp** [comment]
あー、転職したら呪文忘れることはなく、使用回数は覚えていた呪文と同じ数ってのが馴染み深すぎではあります。
回数は最悪0になってもいいですが呪文自体は忘れてないのが良いなあとは思います

**Comment by shiromofufactory** [comment]
転職しても呪文は忘れない仕様ですよ！
