### ISSUE TITLE
local環境browserで遊ぶ

### ISSUE THREAD

**Issue by da0ka** [shiromofufactory/finardry#27]
どうやってlocal環境で遊べますか?

**Comment by shiromofufactory** [comment]
ローカル環境でのプレイはサポートしていません。
配信用Webサイトからプレイください。

ただ、このゲームはPython製ゲームエンジン「Pyxel」で作成していますので、ある程度の知識をお持ちの方であればこの自力で動かすことができるはずです。逆に言うとこれではどうしたらいいかわからない、という場合は諦めたほうがいいです。

**Comment by da0ka** [comment]
配信用pageから分かる範囲で素材は集めてみました。
images、NoSleep.min、pyodide(pyodide.asm.js. pyodide.asm.wasm, pyodide.js, python_stdlib.zip)、custom.js, manifest.json, pyxel.js, sw.jsと処理に関わりそうな物。
repodata.jsonはhttps://repo.anaconda.com/pkgs/free/win-64/ からdownload。ひょっとしてjson以外も全file必要ですか?
fetchはXMLHttpRequestで代用。serviceWorkerはどうにもならず…

**Comment by shiromofufactory** [comment]
すみません、サポートしていないと明言させてもらっていますし、PCローカルで動かすならまだしも、Web上で動かそうとされているのであればなおさら配信用Webサイトでプレイいただきたいのですが。

何か特別な意義があるのであれば明記ください。事情によってはご協力できるかもしれませんが、私から見ますと、たとえば私の知らないところで改造してアップされる、などのリスクをはらむので、現状では回答できないです。
