### ISSUE TITLE
角を曲がるときにナナメ入力すると壁に半マス嵌ることがある

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#3]
半マスハマった状態
![image](https://github.com/shiromofufactory/finardry/assets/78687408/fa26f0d7-d291-4961-b724-4e8392f1811a)

更にぐりぐりやるともっとずれて行って壁の中が少し見えたりもした
![image](https://github.com/shiromofufactory/finardry/assets/78687408/886d3f5a-46f7-4444-8918-2438a7f7d394)

ここから左に歩いたらソフトロック
![image](https://github.com/shiromofufactory/finardry/assets/78687408/e829250c-f636-4b5f-b679-db8e0c07e463)

**Comment by daradarach** [comment]
![image](https://github.com/shiromofufactory/finardry/assets/78687408/c76ac178-9ae4-4ae3-a9cc-a2beda44d54c)
1Fマーフィーズゴーストあたりのここでハマると下にも右にも移動するとソフトロックするので詰みセーブになります

**Comment by daradarach** [comment]
右方向への移動が優先度高いことで起きているようです。
左に歩いて扉を開いたときに、右方向にだけは引き返せたりもします。

**Comment by shiromofufactory** [comment]
これ、私の方では再現できなくてちょっとわからないのですが「右方向への移動が優先度高い」についてはソース上確かにそうなっており、#1 の解消のために修正しました。
なのでおそらく治ったのではないか・・と思ってます。

**Comment by daradarach** [comment]
#1 に伴い直ってそうです。closeした上で万が一また起きるようなら別途issue立てます
