### ISSUE TITLE
要望

### ISSUE THREAD

**Issue by jinbei** [shiromofufactory/finardry#4]
PC版の要望です。

hjklで十字キーと同じ操作ができると嬉しいです。

**Comment by shiromofufactory** [comment]
私のキーボードだと左からHJKLと並んでいるのですが、どのキーがどの方向に対応するイメージでしょうか？
機能的には難しくないのですが。

**Comment by daradarach** [comment]
vim配置ってやつですね。
h左
j下
k上
l右
です。

**Comment by shiromofufactory** [comment]
承知しました。
ver231023で反映しておきました。（Welcome画面上は特に明示していません）
問題なければissueをクローズいただけますか？

**Comment by shiromofufactory** [comment]
@jinbei ↑

**Comment by jinbei** [comment]
説明不足でごめんなさい。
以下のキーと移動の対応です。

h左
j下
k上
l右

2023年10月23日(月) 6:29 daradarach ***@***.***>:

**Comment by jinbei** [comment]
修正ありがとうございます。
