### ISSUE TITLE
PCブラウザで幅を極端に短くするとサイズを戻しても操作不能になる

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#5]
![image](https://github.com/shiromofufactory/finardry/assets/78687408/4f77e23b-280d-4c34-8ff5-3c607df83f1c)

ここから更に幅を縮めるとBGMだけが鳴り続け画面がブラックアウト。二度と操作が効かなくなる

**Comment by shiromofufactory** [comment]
お使いのブラウザを教えていただけますか？
Chromeでは再現しませんでした。
（ただ、修正できない可能性が高いです。）

**Comment by daradarach** [comment]
Win10、Firefoxで特にverを意図的に抑えてないので一般的な最新版だと思います

**Comment by daradarach** [comment]
一応Ver追記、118.0.2 (64 ビット)でした。
![image](https://github.com/shiromofufactory/finardry/assets/78687408/2d2af296-fe06-4ff3-b88a-4147a12bca49)


またMicrosoft Chromium Edgeで再現しないことを確認しました。

**Comment by shiromofufactory** [comment]
こちら対策がとれず申し訳ありません。

使用しているレトロゲームエンジンPyxel側の原因になるため、issueをそちらに記載しました。
https://github.com/kitao/pyxel/issues/500

短期的に解決する可能性はかなり低いです。ご了承ください。

**Comment by shiromofufactory** [comment]
@daradarach 
Pyxelがバージョンアップしたことで解決されたという情報がありました。
私が試してみると、たしかに問題発生しなくなっています。

もしお時間ありましたら念のため一度お試しいただけませんでしょうか？

**Comment by daradarach** [comment]
問題発生しなくなってますね！
公式へのissue報告とご連絡ありがとうございました！
![image](https://github.com/shiromofufactory/finardry/assets/78687408/54340f34-486c-4428-915c-a5ca4228f71f)
