### ISSUE TITLE
タイトル前のClick To Startをパッドでも操作したい

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#6]
PCブラウザでパッド操作中、リセット後にキーボードでないと開始できないのがやや不便

**Comment by shiromofufactory** [comment]
これは使用しているゲームエンジン（Pyxel）の仕様で直せません。
もう少し言うと、ブラウザ自体の仕様としてマウス/タップ操作をしないとそのサイトで音楽を流せないようになっているため、PyxelでClick To Startの画面が入っているはずです。
