### ISSUE TITLE
再読み込みとリセットを差別化し、リセット時は「Finardryのせかいへようこそ」に戻ってほしい

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#7]
再読み込みとリセットを差別化し、リセット時は「Finardryのせかいへようこそ」に戻ってほしい。
おそらくリセット後の再開がスピーディになることも期待できる

**Comment by shiromofufactory** [comment]
ごもっともだと思いました。ありがとうございます。
ver 231023で修正しました。

**Comment by daradarach** [comment]
そうなってましたありがとうございます！
