### ISSUE TITLE
PCブラウザでパッドリセットができない

### ISSUE THREAD

**Issue by daradarach** [shiromofufactory/finardry#8]
「ぜんぶのぼたん」とあるが、ABXではリセットできなかった。
(もしかして十字も全部?十字キーパッドではできない…)

**Comment by shiromofufactory** [comment]
ABXYでリセットできます！

**Comment by daradarach** [comment]
![image](https://github.com/shiromofufactory/finardry/assets/78687408/b4ed6eb9-7ed6-4a2f-91d1-fa535e6b27fd)
同時押しの判定が厳しいみたいで、完全同時押しならリセットできるんですが、
ABX押してY、みたいに押すボタンを増やしていくと同時押し成立してもリセットされないようです。

**Comment by shiromofufactory** [comment]
たしかにそうですね。失礼しました。
ver 231023で修正しました。（問題なさそうならクローズください。他も同様。）

**Comment by daradarach** [comment]
ある程度押しずれてもリセットできるようになりました！
